#! /bin/sh


sxhkd &
compton -b &
feh --bg-scale ${HOME}/Wallpapers/kallodarkmod.png --bg-scale ${HOME}/Wallpapers/nosblus_greyblack.png
xsetroot -cursor_name left_ptr
conky &
#tint2 &
exec ${HOME}/.config/polybar/launch.sh &

bspc wm -O DVI-D-0 HDMI-0
bspc monitor DVI-D-0 -n 0 -d 	1:terminals 2:web  3:misc
bspc monitor HDMI-0 -n 1 -d	4:secondary 5:shit 

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color		"#2B303B"
bspc config focused_border_color 	"#8FA1b3"

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	true
paddingless_monocle		true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop=^4 border=off state=floating rectangle=1280x720+1280+720
bspc rule -a Steam desktop=^5 border=off
bspc rule -a Lutris desktop=^5 border=off follow=off
bspc rule -a URxvt desktop=^4 state=floating follow=on
bspc rule -a Wine desktop=^1 follow=off border=off state=floating
#bspc rule -a Pcmanfm state=floating rectangle=1280x720+960+360
bspc rule -a st border=off
bspc rule -a 'VirtualBox Machine' state=floating
bspc rule -a Eog state=floating
#bspc rule -a vlc state=floating rectangle=1280x720+800+400
