#! /bin/sh

xrandr --output DVI-D-0 --right-of HDMI-0
sxhkd &
compton -b &
feh --bg-scale ${HOME}/Wallpapers/kallodarkmod.png  ${HOME}/Wallpapers/kallomirror.png
xsetroot -cursor_name left_ptr
#hsetroot -solid '#2c4251'
#conky &
exec ${HOME}/.config/polybar/launchbspwm.sh &
bspc config external_rules_command ~/.config/bspwm/external_rules
steam &

# dual monitors
bspc wm -O DVI-D-0 HDMI-0
bspc monitor DVI-D-0 -d 1 2 3
bspc monitor HDMI-0  -d	4 5 6

# single screen
#bspc monitor -d 1:terminals 2:web 3:misc 4:media

bspc config border_width         3
bspc config window_gap          16


#
# get colours from xresources
#
foreground=$(grep *.foreground ~/.extend.Xresources | grep -v URxvt | awk -F ' ' '{print $2}')
background=$(grep *.background ~/.extend.Xresources | grep -v URxvt | awk -F ' ' '{print $2}')
preselecte=$(grep *.color12 ~/.extend.Xresources | awk '{print$2}')

bspc config normal_border_color		$background	
bspc config focused_border_color 	$foreground
bspc config presel_feedback_color	$preselecte

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	true
bspc config paddingless_monocle	false
bspc config initial_polarity second_child

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Spotify:spotify desktop=^4 border=off state=floating follow=off
bspc rule -a Steam desktop=^5 border=on private=on follow=off state=tiled
bspc rule -a Lutris desktop=^5 border=on follow=off
bspc rule -a 'TeamSpeak 3' desktop=^5 follow=off
bspc rule -a URxvt desktop=^4 state=floating follow=on rectangle=1088x1130+1344+166
bspc rule -a Wine desktop=^1 follow=on border=off state=floating layer=above
bspc rule -a Pcmanfm desktop=^3 follow=on
bspc rule -a Firefox private=on
bspc rule -a St border=off
bspc rule -a 'VirtualBox Machine' state=floating
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a Eog state=floating
bspc rule -a Deluge desktop=^6 follow=on
bspc rule -a Gpick state=floating
bspc rule -a vlc state=floating layer=above follow=on rectangle=1280x720+640+360
bspc rule -a Galculator state=floating follow=on
bspc rule -a Polybar layer=below
bspc rule -a Lxappearance state=floating
bspc rule -a Vncviewer state=floating border=on rectangle=1600x900+450+250
bspc rule -a csgo_linux64 desktop=^1 follow=on
