#! /bin/sh


sxhkd &
compton -b &
feh --bg-scale ${HOME}/Wallpapers/kallodarkmod.png --bg-scale ${HOME}/Wallpapers/kallomirror.png
xsetroot -cursor_name left_ptr
conky &
#tint2 &
exec ${HOME}/.config/polybar/launch.sh &
steam &

bspc wm -O DVI-D-0 HDMI-0
bspc monitor DVI-D-0 -n 0 -d 	1:terminals 2:web  3:misc
bspc monitor HDMI-0 -n 1 -d	4:media 5:games 6:shit

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color		"#2B303B"
bspc config focused_border_color 	"#8FA1b3"

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	true
bspc config paddingless_monocle	false


bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop=^4 border=off state=floating follow=off
bspc rule -a Steam desktop=^5 border=on private=on follow=off
bspc rule -a Lutris desktop=^5 border=on follow=off
bspc rule -a 'TeamSpeak 3' desktop=^5 follow=off
bspc rule -a URxvt desktop=^4 state=floating follow=off
bspc rule -a Wine desktop=^1 follow=off border=off state=floating
#bspc rule -a Pcmanfm state=floating rectangle=1280x720+960+360
bspc rule -a Firefox private=on
bspc rule -a St border=off
bspc rule -a 'VirtualBox Machine' state=floating
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a Eog state=floating
bspc rule -a Deluge desktop=^6 follow=on

