#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
	(Spotify) echo desktop=^4\ border=on\ state=floating\ follow=off\ rectangle=1216x1290+64+86;;
	('')
		case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
			(spotify) echo desktop=^4\ border=on\ state=floating\ follow=off\ rectangle=1216x1290+64+86;;
		esac;;
esac;
